[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x585273"
blue = "0x65b2ff"
cyan = "0x63f2f1"
green = "0x62d196"
magenta = "0xa37acc"
red = "0xf02e6e"
white = "0x8a889d"
yellow = "0xf2b482"

[colors.cursor]
cursor = "0xa1efd3"
text = "0x1e1c31"

[colors.normal]
black = "0x1e1c31"
blue = "0x91ddff"
cyan = "0x87dfeb"
green = "0xa1efd3"
magenta = "0xd4bfff"
red = "0xf48fb1"
white = "0xcbe3e7"
yellow = "0xffe6b3"

[colors.primary]
background = "0x1e1c31"
foreground = "0xcbe3e7"

[font]
size = 10.5

[font.normal]
#family = "Intel One Mono"
#family = "Hack Nerd Font Mono"
family = "CaskaydiaCove NFM"
#family = "UbuntuMono Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove NFM"
#family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaCove NFM"
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

#[schemes.name.bright]
#black = "0x585273"
#blue = "0x65b2ff"
#cyan = "0x63f2f1"
#green = "0x62d196"
#magenta = "0xa37acc"
#red = "0xf02e6e"
#white = "0x8a889d"
#yellow = "0xf2b482"
#
#[schemes.name.cursor]
#cursor = "0xa1efd3"
#text = "0x1e1c31"
#
#[schemes.name.normal]
#black = "0x1e1c31"
#blue = "0x91ddff"
#cyan = "0x87dfeb"
#green = "0xa1efd3"
#magenta = "0xd4bfff"
#red = "0xf48fb1"
#white = "0xcbe3e7"
#yellow = "0xffe6b3"
#
#[schemes.name.primary]
#background = "0x1e1c31"
#foreground = "0xcbe3e7"

[window]
decorations = "none"
opacity = 0.8
blur = true

[window.dimensions]
columns = 85
lines = 25

[window.padding]
x = 0
y = 0

[window.position]
x = 120
y = 120
